import React, { useState, useEffect } from 'react';
import { AdviceCard } from '../types';
import { Share2, Check, Copy, Sparkles, Award, Star, HelpCircle, Twitter, Linkedin } from 'lucide-react';
import { motion } from 'motion/react';

interface AdviceCardGenProps {
  initialCard: AdviceCard | null;
}

export default function AdviceCardGen({ initialCard }: AdviceCardGenProps) {
  const [card, setCard] = useState<AdviceCard | null>(null);
  const [styleMode, setStyleMode] = useState<'minimal' | 'detailed' | 'branded'>('branded');
  const [copystate, setCopystate] = useState(false);

  useEffect(() => {
    if (initialCard) {
      setCard({ ...initialCard });
      setStyleMode(initialCard.styling || 'branded');
    }
  }, [initialCard]);

  if (!card) {
    return (
      <div className="bg-immersive-card border border-immersive-border rounded-2xl p-8 text-center text-immersive-dim font-sans transition-all">
        <HelpCircle className="h-8 w-8 mx-auto text-immersive-accent mb-3" />
        No active decision outputs mapped. Submit a query to trigger your automated Advice Card.
      </div>
    );
  }

  // Handle Editing
  const updateCardField = (key: keyof AdviceCard, val: any) => {
    setCard(prev => prev ? { ...prev, [key]: val } : null);
  };

  const updateCardStep = (index: number, val: string) => {
    setCard(prev => {
      if (!prev) return null;
      const updatedSteps = [...prev.steps];
      updatedSteps[index] = val;
      return { ...prev, steps: updatedSteps };
    });
  };

  const handleCopy = () => {
    // Generate beautiful clean Markdown quote block for LinkedIn or Twitter
    const markdownQuote = `🔥 KEY DECISION INSIGHT BY MENTORAI:
"${card.headline}"
  
🏛️ Core Framework: ${card.coreFramework}
  
🪜 Actionable Steps:
${card.steps.map((step, i) => `${i + 1}. ${step}`).join("\n")}
  
💡 Top Takeaway:
"${card.takeaway}"
  
---
Generated by MentorAI — Your billion-dollar brain on demand.
#Productivity #Business #Mentorship #DecisionOS`;

    navigator.clipboard.writeText(markdownQuote);
    setCopystate(true);
    setTimeout(() => setCopystate(false), 2200);
  };

  const shareOnTwitter = () => {
    if (!card) return;
    const text = `🔥 KEY DECISION INSIGHT BY MENTORAI:
"${card.headline}"

🏛️ Core Framework: ${card.coreFramework}
💡 Takeaway: "${card.takeaway}"

Generated via MentorAI — Your billion-dollar brain on demand.`;
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&hashtags=Business,Mentorship,DecisionOS,AI`;
    window.open(url, '_blank', 'noreferrer');
  };

  const shareOnLinkedin = () => {
    if (!card) return;
    const text = `🔥 KEY DECISION INSIGHT BY MENTORAI:
"${card.headline}"

🏛️ Core Framework: ${card.coreFramework}
💡 Takeaway: "${card.takeaway}"

Generated via MentorAI — Your billion-dollar brain on demand.`;
    const url = `https://www.linkedin.com/feed/?shareActive=true&text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'noreferrer');
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
      
      {/* Visual Workspace Canvas */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h4 className="font-sans font-bold text-xs uppercase text-[#71717A] tracking-wider">Social Advice Card Workspace</h4>
          <span className="text-[10px] font-mono text-zinc-500 uppercase">Interactive Preview</span>
        </div>

        {/* The Card template render container */}
        <div className="relative overflow-hidden rounded-2xl border border-[#1A1A1E] shadow-2xl">
          {styleMode === 'minimal' && (
            <div className="bg-[#050507] p-8 min-h-[300px] flex flex-col justify-between font-mono text-zinc-300">
              <div className="space-y-4">
                <p className="text-zinc-600 text-[10px]">// DECISION INSIGHT PLATFORM — MENTORAI</p>
                <h5 className="text-white text-base font-bold tracking-tight leading-snug uppercase">
                  &gt; {card.headline || "Action Strategy Outline"}
                </h5>
                <p className="text-[11px] text-[#00FFC2] font-semibold uppercase">Framework: {card.coreFramework}</p>
                <ul className="space-y-1.5 text-xs text-zinc-400 pl-4 list-disc">
                  {card.steps.map((s, idx) => (
                    <li key={idx} className="leading-relaxed">{s}</li>
                  ))}
                </ul>
              </div>
              <div className="mt-8 pt-4 border-t border-[#1A1A1E] flex justify-between text-[9px] text-[#71717A] uppercase tracking-widest">
                <span>Confidence: 94%</span>
                <span>STATUS: SECURE_HEALED</span>
              </div>
            </div>
          )}

          {styleMode === 'detailed' && (
            <div className="bg-[#0C0C0F] border border-[#1A1A1E] p-8 min-h-[300px] flex flex-col justify-between font-sans text-slate-300">
              <div className="space-y-6">
                <div className="flex items-center gap-2 border-b border-[#1A1A1E] pb-3">
                  <Award className="h-5 w-5 text-[#00FFC2]" />
                  <span className="font-mono text-[10px] tracking-widest text-[#71717A] uppercase">Executive Directive</span>
                </div>
                <div>
                  <h5 className="text-lg font-extrabold text-white tracking-tight mb-2 leading-snug">
                    {card.headline}
                  </h5>
                  <p className="text-xs text-[#00FFC2] font-mono italic mb-4">Utilizing: {card.coreFramework}</p>
                  <p className="text-sm text-zinc-400 leading-relaxed mb-4">{card.takeaway}</p>
                </div>
              </div>
              <div className="text-[10px] font-mono text-slate-500 pt-6">
                PRODUCED ON-DEMAND BY MENTORAI
              </div>
            </div>
          )}

          {styleMode === 'branded' && (
            <div className="bg-gradient-to-tr from-[#0C0C0F] via-[#0C0C0F]/80 to-[#121217] p-8 min-h-[300px] flex flex-col justify-between font-sans text-slate-200 relative">
              <div className="absolute top-0 right-0 w-32 h-32 bg-[#00FFC2]/5 rounded-full blur-2xl top-right pointer-events-none" />
              <div className="space-y-6 z-10">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-[#00FFC2] uppercase tracking-wider font-mono text-[9px]">
                    <Sparkles className="h-3 w-3 animate-pulse" style={{ animationDuration: '3s' }} />
                    Billionaire Mentorship Blueprints
                  </div>
                  <Star className="h-4 w-4 text-[#00FFC2] fill-[#00FFC2]/30" />
                </div>

                <div className="space-y-3">
                  <h5 className="text-xl font-black text-white leading-tight tracking-tight">
                    {card.headline}
                  </h5>
                  <div className="h-[2px] w-12 bg-[#00FFC2] rounded" />
                  <p className="font-mono text-[10px] uppercase text-zinc-400 tracking-wide">
                    FRAMEWORK: <span className="text-[#00FFC2]">{card.coreFramework}</span>
                  </p>
                </div>

                <div className="bg-[#050507]/80 border border-[#1A1A1E] p-4 rounded-xl backdrop-blur-sm">
                  <p className="text-xs text-zinc-300 leading-relaxed italic">
                    "{card.takeaway}"
                  </p>
                </div>
              </div>

              <div className="flex items-center justify-between text-[9px] font-mono text-[#71717A] uppercase tracking-widest pt-8 z-10">
                <span>Verified by MentorAI</span>
                <span>SYSTEM VERSION 2.5</span>
              </div>
            </div>
          )}
        </div>

        {/* Copy & Social CTA Actions */}
        <div className="space-y-2">
          <button
            onClick={handleCopy}
            className="w-full bg-immersive-card hover:bg-immersive-aside text-immersive-text-white font-sans font-bold text-sm tracking-tight border border-immersive-border p-3 rounded-xl flex items-center justify-center gap-2 transition-all duration-200 shadow-xl cursor-pointer"
          >
            {copystate ? (
              <>
                <Check className="h-4 w-4 text-immersive-accent" />
                Copied! ready for social platforms ✓
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 text-immersive-accent" />
                Copy formatted Advice Card Quote
              </>
            )}
          </button>

          <div className="grid grid-cols-2 gap-2 animate-fade-in">
            <button
              type="button"
              onClick={shareOnTwitter}
              className="bg-immersive-bg hover:bg-immersive-aside border border-immersive-border text-immersive-text hover:text-white p-2.5 rounded-lg flex items-center justify-center gap-1.5 text-xs font-semibold font-sans cursor-pointer transition-colors duration-200"
            >
              <Twitter className="h-3.5 w-3.5 text-sky-400" />
              Share to Twitter / X
            </button>
            <button
              type="button"
              onClick={shareOnLinkedin}
              className="bg-immersive-bg hover:bg-immersive-aside border border-immersive-border text-immersive-text hover:text-white p-2.5 rounded-lg flex items-center justify-center gap-1.5 text-xs font-semibold font-sans cursor-pointer transition-colors duration-200"
            >
              <Linkedin className="h-3.5 w-3.5 text-blue-500" />
              Share to LinkedIn
            </button>
          </div>
        </div>
      </div>

      {/* Editor & Style Customizer */}
      <div className="space-y-6">
        <div>
          <h4 className="font-sans font-bold text-xs uppercase text-immersive-dim tracking-wider mb-3">Card Canvas Theme</h4>
          <div className="grid grid-cols-3 gap-2">
            {(['branded', 'detailed', 'minimal'] as const).map((mode) => (
              <button
                key={mode}
                onClick={() => setStyleMode(mode)}
                className={`p-2.5 rounded-lg border text-xs font-semibold capitalize font-sans transition-all duration-200 cursor-pointer ${
                  styleMode === mode
                    ? 'border-immersive-accent bg-immersive-accent/10 text-immersive-accent font-bold'
                    : 'border-immersive-border bg-immersive-bg text-immersive-dim hover:border-immersive-accent/50'
                }`}
              >
                {mode === 'branded' ? '✨ Branded' : mode === 'detailed' ? '📋 Executive' : '💻 Terminal'}
              </button>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <h4 className="font-sans font-bold text-xs uppercase text-immersive-dim tracking-wider border-b border-immersive-border pb-2">Customize Metadata</h4>
          
          <div className="space-y-2">
            <label className="text-[10px] font-mono uppercase text-immersive-dim">Card Title Headline</label>
            <input
              type="text"
              value={card.headline}
              onChange={(e) => updateCardField('headline', e.target.value)}
              className="w-full bg-immersive-bg border border-immersive-border text-immersive-text rounded-lg p-2.5 text-xs focus:outline-none focus:border-immersive-accent transition-all"
            />
          </div>

          <div className="space-y-2">
            <label className="text-[10px] font-mono uppercase text-immersive-dim">Core Blueprint Framework</label>
            <input
              type="text"
              value={card.coreFramework}
              onChange={(e) => updateCardField('coreFramework', e.target.value)}
              className="w-full bg-immersive-bg border border-immersive-border text-immersive-text rounded-lg p-2.5 text-xs focus:outline-none focus:border-immersive-accent transition-all"
            />
          </div>

          <div className="space-y-3">
            <label className="text-[10px] font-mono uppercase text-immersive-dim block">Edit Actionable Milestones</label>
            {card.steps.map((step, idx) => (
              <div key={idx} className="flex gap-2">
                <span className="font-mono text-immersive-dim border border-immersive-border bg-immersive-card w-10 h-8 flex items-center justify-center text-xs rounded-lg select-none">
                  {idx + 1}
                </span>
                <input
                  type="text"
                  value={step}
                  onChange={(e) => updateCardStep(idx, e.target.value)}
                  className="flex-1 bg-immersive-bg border border-immersive-border text-immersive-text rounded-lg px-2.5 py-1 text-xs focus:outline-none focus:border-immersive-accent transition-all"
                />
              </div>
            ))}
          </div>

          <div className="space-y-2">
            <label className="text-[10px] font-mono uppercase text-immersive-dim">Summary Take-Away</label>
            <textarea
              value={card.takeaway}
              rows={3}
              onChange={(e) => updateCardField('takeaway', e.target.value)}
              className="w-full bg-immersive-bg border border-immersive-border text-immersive-text rounded-lg p-2.5 text-xs focus:outline-none focus:border-immersive-accent resize-none leading-relaxed transition-all"
            />
          </div>
        </div>
      </div>

    </div>
  );
}
